machine:
  name: sakura
  hostname_match: "sakura"

paths:
  imagenet_root: "/export/scratch1/home/melle/datasets/imagenet"
  log_dir: "logs"

data_defaults:
  num_workers: 16
  gpu_transforms: false

wandb:
  tags: ["sakura", "rtx3090"]
